'use strict';var f,aa=require("vega-embed"),ba=Object.freeze({esVersion:6,assumingES6:!0,productionMode:!0,linkerVersion:"1.10.0",fileLevelThis:this}),ca;function da(a){for(var b in a)return b}function h(a){this.Xa=a}h.prototype.toString=function(){return String.fromCharCode(this.Xa)};
function ea(a){switch(typeof a){case "string":return"java.lang.String";case "number":return"number"===typeof a&&(a|0)===a&&1/a!==1/-0?a<<24>>24===a?"java.lang.Byte":a<<16>>16===a?"java.lang.Short":"java.lang.Integer":"number"!==typeof a||a===a&&Math.fround(a)!==a?"java.lang.Double":"java.lang.Float";case "boolean":return"java.lang.Boolean";case "undefined":return"java.lang.Void";default:return null===a?a.Bd():a instanceof l?"java.lang.Long":a instanceof h?"java.lang.Character":a&&a.$classData?a.$classData.name:
null.Cd()}}function fa(a,b){switch(typeof a){case "string":return a===b;case "number":return Object.is(a,b);case "boolean":return a===b;case "undefined":return a===b;default:return a&&a.$classData||null===a?b=a.y(b):a instanceof l?b instanceof l?(a=n(a),b=n(b),b=a.l===b.l&&a.k===b.k):b=!1:b=a instanceof h?b instanceof h?p(a)===p(b):!1:q.prototype.y.call(a,b),b}}
function ha(a){switch(typeof a){case "string":return r(a);case "number":return ia(a);case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.$classData||null===a?a=a.E():a instanceof l?(a=n(a),a=a.l^a.k):a=a instanceof h?p(a):q.prototype.E.call(a),a}}function ja(a){return void 0===a?"undefined":a.toString()}var ka=0,la=new WeakMap;
function ma(a){switch(typeof a){case "string":return r(a);case "number":return ia(a);case "bigint":var b=0;for(a<BigInt(0)&&(a=~a);a!==BigInt(0);)b^=Number(BigInt.asIntN(32,a)),a>>=BigInt(32);return b;case "boolean":return a?1231:1237;case "undefined":return 0;case "symbol":return a=a.description,void 0===a?0:r(a);default:if(null===a)return 0;b=la.get(a);void 0===b&&(ka=b=ka+1|0,la.set(a,b));return b}}function p(a){return null===a?0:a.Xa}function n(a){return null===a?ca:a}function q(){}
q.prototype.constructor=q;function u(){}u.prototype=q.prototype;q.prototype.E=function(){return ma(this)};q.prototype.y=function(a){return this===a};q.prototype.j=function(){var a=this.E();return ea(this)+"@"+(+(a>>>0)).toString(16)};q.prototype.toString=function(){return this.j()};function v(a){if("number"===typeof a){this.d=Array(a);for(var b=0;b<a;b++)this.d[b]=null}else this.d=a}v.prototype=new u;v.prototype.constructor=v;function na(){}na.prototype=v.prototype;
function oa(a){if("number"===typeof a){this.d=Array(a);for(var b=0;b<a;b++)this.d[b]=!1}else this.d=a}oa.prototype=new u;oa.prototype.constructor=oa;function pa(a){this.d="number"===typeof a?new Uint16Array(a):a}pa.prototype=new u;pa.prototype.constructor=pa;function qa(a){this.d="number"===typeof a?new Int8Array(a):a}qa.prototype=new u;qa.prototype.constructor=qa;function ra(a){this.d="number"===typeof a?new Int16Array(a):a}ra.prototype=new u;ra.prototype.constructor=ra;
function sa(a){this.d="number"===typeof a?new Int32Array(a):a}sa.prototype=new u;sa.prototype.constructor=sa;function ta(a){if("number"===typeof a){this.d=Array(a);for(var b=0;b<a;b++)this.d[b]=ca}else this.d=a}ta.prototype=new u;ta.prototype.constructor=ta;function ua(a){this.d="number"===typeof a?new Float32Array(a):a}ua.prototype=new u;ua.prototype.constructor=ua;function va(a){this.d="number"===typeof a?new Float64Array(a):a}va.prototype=new u;va.prototype.constructor=va;
function wa(){this.J=void 0;this.$=this.r=null;this.aa=0;this.Bb=null;this.I="";this.S=this.Z=void 0;this.name="";this.isJSClass=this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function w(a,b,c,d){var g=new wa;g.r={};g.Bb=a;g.I=b;g.S=e=>e===g;g.name=c;g.isPrimitive=!0;g.isInstance=()=>!1;void 0!==d&&(g.Z=xa(g,d));return g}
function x(a,b,c){var d=new wa,g=da(a);d.r=c;d.I="L"+b+";";d.S=e=>!!e.r[g];d.name=b;d.isInterface=!1;d.isInstance=e=>!!(e&&e.$classData&&e.$classData.r[g]);return d}function xa(a,b,c){var d=new wa;b.prototype.$classData=d;var g="["+a.I;d.J=b;d.r={a:1,Ga:1,c:1};d.$=a;d.aa=1;d.I=g;d.name=g;d.isArrayClass=!0;d.S=c||(e=>d===e);d.isInstance=e=>e instanceof b;return d}
function ya(a){function b(k){if("number"===typeof k){this.d=Array(k);for(var m=0;m<k;m++)this.d[m]=null}else this.d=k}var c=new wa;b.prototype=new na;b.prototype.constructor=b;var d=a.$||a,g=a.aa+1;b.prototype.$classData=c;a="["+a.I;c.J=b;c.r={a:1,Ga:1,c:1};c.$=d;c.aa=g;c.I=a;c.name=a;c.isArrayClass=!0;var e=k=>{var m=k.aa;return m===g?d.S(k.$):m>g&&d===y};c.S=e;c.isInstance=k=>{k=k&&k.$classData;return!!k&&(k===c||e(k))};return c}function z(a){a.Z||(a.Z=ya(a));return a.Z}var y=new wa;y.r={a:1};
y.I="Ljava.lang.Object;";y.S=a=>!a.isPrimitive;y.name="java.lang.Object";y.isInstance=a=>null!==a;y.Z=xa(y,v,a=>{var b=a.aa;return 1===b?!a.$.isPrimitive:1<b});q.prototype.$classData=y;w(void 0,"V","void",void 0);w(!1,"Z","boolean",oa);w(0,"C","char",pa);w(0,"B","byte",qa);w(0,"S","short",ra);w(0,"I","int",sa);var za=w(null,"J","long",ta);w(0,"F","float",ua);w(0,"D","double",va);
function Aa(){this.bb=this.oa=this.ba=null;Ba=this;this.ba=new ArrayBuffer(8);this.oa=new Int32Array(this.ba,0,2);new Float32Array(this.ba,0,2);this.bb=new Float64Array(this.ba,0,1);this.oa[0]=16909060;new Int8Array(this.ba,0,8)}Aa.prototype=new u;Aa.prototype.constructor=Aa;function Ca(a,b){var c=b|0;if(c===b&&-Infinity!==1/b)return c;a.bb[0]=b;return(a.oa[0]|0)^(a.oa[1]|0)}Aa.prototype.$classData=x({Pb:0},"java.lang.FloatingPointBits$",{Pb:1,a:1});var Ba;
function Da(){Ba||(Ba=new Aa);return Ba}function Ea(){this.db=null;Fa=this;this.db=new A(!1);new A(!0)}Ea.prototype=new u;Ea.prototype.constructor=Ea;Ea.prototype.$classData=x({Yb:0},"java.lang.System$Streams$",{Yb:1,a:1});var Fa;function Ga(){Fa||(Fa=new Ea);return Fa}
function Ha(){this.eb=this.Ha=null;Ia=this;var a={"java.version":"1.8","java.vm.specification.version":"1.8","java.vm.specification.vendor":"Oracle Corporation","java.vm.specification.name":"Java Virtual Machine Specification","java.vm.name":"Scala.js"};a["java.vm.version"]=ba.linkerVersion;a["java.specification.version"]="1.8";a["java.specification.vendor"]="Oracle Corporation";a["java.specification.name"]="Java Platform API Specification";a["file.separator"]="/";a["path.separator"]=":";a["line.separator"]=
"\n";this.Ha=a;this.eb=null}Ha.prototype=new u;Ha.prototype.constructor=Ha;function Ja(a,b,c){null!==a.Ha?(Ka||(Ka=new La),a=a.Ha,Ma||(Ma=new Na),b=Ma.gb.call(a,b)?a[b]:c):b=Ja(a.eb,b,c);return b}Ha.prototype.$classData=x({Zb:0},"java.lang.System$SystemProperties$",{Zb:1,a:1});var Ia;function La(){}La.prototype=new u;La.prototype.constructor=La;La.prototype.$classData=x({dc:0},"java.lang.Utils$",{dc:1,a:1});var Ka;function Na(){this.gb=null;Ma=this;this.gb=Object.prototype.hasOwnProperty}
Na.prototype=new u;Na.prototype.constructor=Na;Na.prototype.$classData=x({ec:0},"java.lang.Utils$Cache$",{ec:1,a:1});var Ma;function Oa(){}Oa.prototype=new u;Oa.prototype.constructor=Oa;Oa.prototype.$classData=x({fc:0},"java.util.Arrays$",{fc:1,a:1});var Pa;function Qa(){}Qa.prototype=new u;Qa.prototype.constructor=Qa;Qa.prototype.$classData=x({Fb:0},"mdocjs$",{Fb:1,a:1});var Ra;function l(a,b){this.l=a;this.k=b}l.prototype=new u;l.prototype.constructor=l;
l.prototype.y=function(a){return a instanceof l?this.l===a.l&&this.k===a.k:!1};l.prototype.E=function(){return this.l^this.k};l.prototype.j=function(){Sa();var a=this.l,b=this.k;return b===a>>31?""+a:0>b?"-"+Ta(-a|0,0!==a?~b:-b|0):Ta(a,b)};l.prototype.$classData=x({Ib:0},"org.scalajs.linker.runtime.RuntimeLong",{Ib:1,a:1});
function Ta(a,b){if(0===(-2097152&b))b=""+(4294967296*b+ +(a>>>0));else{var c=(32+Math.clz32(1E9)|0)-(0!==b?Math.clz32(b):32+Math.clz32(a)|0)|0,d=c,g=0===(32&d)?1E9<<d:0;d=0===(32&d)?5E8>>>(31-d|0)|0|0<<d:1E9<<d;var e=a,k=b;for(a=b=0;0<=c&&0!==(-2097152&k);){var m=e,t=k,ec=g,J=d;if(t===J?(-2147483648^m)>=(-2147483648^ec):(-2147483648^t)>=(-2147483648^J))m=k,t=d,k=e-g|0,m=(-2147483648^k)>(-2147483648^e)?-1+(m-t|0)|0:m-t|0,e=k,k=m,32>c?b|=1<<c:a|=1<<c;c=-1+c|0;m=d>>>1|0;g=g>>>1|0|d<<31;d=m}c=k;if(0===
c?-1147483648<=(-2147483648^e):-2147483648<=(-2147483648^c))c=4294967296*k+ +(e>>>0),e=c/1E9,g=e/4294967296|0,d=b,b=e=d+(e|0)|0,a=(-2147483648^e)<(-2147483648^d)?1+(a+g|0)|0:a+g|0,e=c%1E9|0;c=""+e;b=""+(4294967296*a+ +(b>>>0))+"000000000".substring(c.length|0)+c}return b}function Ua(){this.ia=0}Ua.prototype=new u;Ua.prototype.constructor=Ua;function Va(a,b,c){return 0>c?-(4294967296*+((0!==b?~c:-c|0)>>>0)+ +((-b|0)>>>0)):4294967296*c+ +(b>>>0)}
Ua.prototype.$classData=x({Jb:0},"org.scalajs.linker.runtime.RuntimeLong$",{Jb:1,a:1});var Wa;function Sa(){Wa||(Wa=new Ua);return Wa}function Xa(a,b,c,d){if(a.e())a=""+b+d;else{var g=a.ja,e=new Ya;e.x=Za(new B);a=g.call(a,e,b,c,d).x.b}return a}function $a(a,b,c,d,g){var e=b.x;0!==(c.length|0)&&(e.b=""+e.b+c);a=a.o();if(a.h())for(c=a.f(),e.b=""+e.b+c;a.h();)e.b=""+e.b+d,c=a.f(),e.b=""+e.b+c;0!==(g.length|0)&&(e.b=""+e.b+g);return b}
function ab(){this.zb=null;bb=this;this.zb=new v(0);new (z(z(y)).J)(0);new (z(z(z(y))).J)(0);new (z(z(z(z(y)))).J)(0);new (z(z(z(z(z(y))))).J)(0);new (z(z(z(z(z(z(y)))))).J)(0)}ab.prototype=new u;ab.prototype.constructor=ab;ab.prototype.$classData=x({nd:0},"scala.collection.immutable.VectorStatics$",{nd:1,a:1});var bb;function cb(){bb||(bb=new ab);return bb}function db(){}db.prototype=new u;db.prototype.constructor=db;
db.prototype.$classData=x({Nc:0},"scala.collection.package$$colon$plus$",{Nc:1,a:1});var eb;function fb(){}fb.prototype=new u;fb.prototype.constructor=fb;fb.prototype.$classData=x({Oc:0},"scala.collection.package$$plus$colon$",{Oc:1,a:1});var gb;function hb(){}hb.prototype=new u;hb.prototype.constructor=hb;hb.prototype.$classData=x({rc:0},"scala.math.Ordered$",{rc:1,a:1});var ib;
function jb(){this.lb=null;kb=this;lb||(lb=new C);lb||(lb=new C);mb||(mb=new nb);ob||(ob=new pb);D();qb();this.lb=E();rb||(rb=new F);gb||(gb=new fb);eb||(eb=new db);sb||(sb=new tb);G();ub();vb||(vb=new wb);xb||(xb=new yb);zb||(zb=new Ab);Bb||(Bb=new Cb);Db||(Db=new Eb);Fb||(Fb=new Gb);ib||(ib=new hb);Hb||(Hb=new Ib);Jb||(Jb=new Kb);Lb||(Lb=new H);Mb||(Mb=new I)}jb.prototype=new u;jb.prototype.constructor=jb;jb.prototype.$classData=x({tc:0},"scala.package$",{tc:1,a:1});var kb;function Nb(){}
Nb.prototype=new u;Nb.prototype.constructor=Nb;function K(a,b,c){if(b===c)c=!0;else if(Ob(b))a:if(Ob(c))c=Pb(b,c);else{if(c instanceof h){if("number"===typeof b){c=+b===p(c);break a}if(b instanceof l){a=n(b);b=a.k;c=p(c);c=a.l===c&&b===c>>31;break a}}c=null===b?null===c:fa(b,c)}else c=b instanceof h?Qb(b,c):null===b?null===c:fa(b,c);return c}
function Pb(a,b){if("number"===typeof a){a=+a;if("number"===typeof b)return a===+b;if(b instanceof l){var c=n(b);b=c.l;c=c.k;return a===Va(Sa(),b,c)}return!1}if(a instanceof l){c=n(a);a=c.l;c=c.k;if(b instanceof l){b=n(b);var d=b.k;return a===b.l&&c===d}return"number"===typeof b?(b=+b,Va(Sa(),a,c)===b):!1}return null===a?null===b:fa(a,b)}
function Qb(a,b){if(b instanceof h)return p(a)===p(b);if(Ob(b)){if("number"===typeof b)return+b===p(a);if(b instanceof l){b=n(b);var c=b.k;a=p(a);return b.l===a&&c===a>>31}return null===b?null===a:fa(b,a)}return null===a&&null===b}Nb.prototype.$classData=x({td:0},"scala.runtime.BoxesRunTime$",{td:1,a:1});var Rb;function L(){Rb||(Rb=new Nb);return Rb}function Sb(){}Sb.prototype=new u;Sb.prototype.constructor=Sb;
function M(a,b){if(null===b)return 0;if("number"===typeof b){a=+b;b=2147483647<a?2147483647:-2147483648>a?-2147483648:a|0;if(b===a)a=b;else{b=Sa();if(-0x7fffffffffffffff>a){b.ia=-2147483648;var c=0}else if(0x7fffffffffffffff<=a)b.ia=2147483647,c=-1;else{c=a|0;var d=a/4294967296|0;b.ia=0>a&&0!==c?-1+d|0:d}b=b.ia;a=Va(Sa(),c,b)===a?c^b:Ca(Da(),a)}return a}return b instanceof l?(a=n(b),b=new l(a.l,a.k),a=b.l,b=b.k,b===a>>31?a:a^b):ha(b)}
Sb.prototype.$classData=x({wd:0},"scala.runtime.Statics$",{wd:1,a:1});var Wb;function N(){Wb||(Wb=new Sb);return Wb}function Xb(){}Xb.prototype=new u;Xb.prototype.constructor=Xb;Xb.prototype.$classData=x({sd:0},"scala.scalajs.runtime.package$",{sd:1,a:1});var Yb;function Zb(a){this.mb=a}Zb.prototype=new u;Zb.prototype.constructor=Zb;Zb.prototype.j=function(){return"DynamicVariable("+this.mb+")"};Zb.prototype.$classData=x({uc:0},"scala.util.DynamicVariable",{uc:1,a:1});function $b(){}
$b.prototype=new u;$b.prototype.constructor=$b;function ac(){}ac.prototype=$b.prototype;function O(a,b){a=bc(a,b);return-430675100+Math.imul(5,a<<13|a>>>19|0)|0}function bc(a,b){b=Math.imul(-862048943,b);b=Math.imul(461845907,b<<15|b>>>17|0);return a^b}function P(a){a=Math.imul(-2048144789,a^(a>>>16|0));a=Math.imul(-1028477387,a^(a>>>13|0));return a^(a>>>16|0)}function cc(){}cc.prototype=new u;cc.prototype.constructor=cc;cc.prototype.$classData=x({Gb:0},"viz.doc.showJsDocs$",{Gb:1,a:1});var dc;
function fc(a){0===(32&a.na)<<24>>24&&0===(32&a.na)<<24>>24&&(a.ab=new sa(new Int32Array([1632,1776,1984,2406,2534,2662,2790,2918,3046,3174,3302,3430,3664,3792,3872,4160,4240,6112,6160,6470,6608,6784,6800,6992,7088,7232,7248,42528,43216,43264,43472,43600,44016,65296,66720,69734,69872,69942,70096,71360,120782,120792,120802,120812,120822])),a.na=(32|a.na)<<24>>24);return a.ab}function gc(){this.ab=null;this.na=0}gc.prototype=new u;gc.prototype.constructor=gc;
gc.prototype.$classData=x({Ob:0},"java.lang.Character$",{Ob:1,a:1,c:1});var hc;function ic(a){throw new jc('For input string: "'+a+'"');}function kc(){}kc.prototype=new u;kc.prototype.constructor=kc;kc.prototype.$classData=x({Rb:0},"java.lang.Integer$",{Rb:1,a:1,c:1});var lc;function Ob(a){return"number"===typeof a||a instanceof l}function Q(a,b){a.fb=b;a.$b=null;a.ac=!0;a.bc=!0;a.$a()}
class mc extends Error{constructor(){super();this.$b=this.fb=null;this.bc=this.ac=!1}ma(){return this.fb}$a(){"[object Error]"!==Object.prototype.toString.call(this)&&void 0!==Error.captureStackTrace&&Error.captureStackTrace(this)}j(){var a=ea(this),b=this.ma();return null===b?a:a+": "+b}E(){return q.prototype.E.call(this)}y(a){return q.prototype.y.call(this,a)}get message(){var a=this.ma();return null===a?"":a}get name(){return ea(this)}toString(){return this.j()}}
function nc(){this.Ja=this.Ia=0;this.jc=!1}nc.prototype=new u;nc.prototype.constructor=nc;function oc(a){var b=a.Ja,c=15525485*b+11;b=16777215&((c/16777216|0)+(16777215&(1502*b+15525485*a.Ia|0))|0);c=16777215&(c|0);a.Ia=b;a.Ja=c;return(b<<8|c>>16)>>>1|0}nc.prototype.$classData=x({hc:0},"java.util.Random",{hc:1,a:1,c:1});function pc(){var a=4294967296*+Math.random();a=+Math.floor(a)-2147483648;return 2147483647<a?2147483647:-2147483648>a?-2147483648:a|0}function qc(){}qc.prototype=new u;
qc.prototype.constructor=qc;qc.prototype.$classData=x({ic:0},"java.util.Random$",{ic:1,a:1,c:1});var rc;function sc(){this.jb=null;tc=this;this.jb=new Zb(Ga().db);Ga()}sc.prototype=new u;sc.prototype.constructor=sc;sc.prototype.$classData=x({kc:0},"scala.Console$",{kc:1,a:1,Dd:1});var tc;function F(){}F.prototype=new u;F.prototype.constructor=F;F.prototype.j=function(){return"::"};F.prototype.$classData=x({Qc:0},"scala.collection.immutable.$colon$colon$",{Qc:1,a:1,c:1});var rb;function yb(){}
yb.prototype=new u;yb.prototype.constructor=yb;yb.prototype.$classData=x({gd:0},"scala.collection.immutable.Range$",{gd:1,a:1,c:1});var xb;function wb(){}wb.prototype=new u;wb.prototype.constructor=wb;wb.prototype.$classData=x({pd:0},"scala.collection.mutable.StringBuilder$",{pd:1,a:1,c:1});var vb;function Cb(){}Cb.prototype=new u;Cb.prototype.constructor=Cb;Cb.prototype.$classData=x({oc:0},"scala.math.Fractional$",{oc:1,a:1,c:1});var Bb;function Eb(){}Eb.prototype=new u;
Eb.prototype.constructor=Eb;Eb.prototype.$classData=x({pc:0},"scala.math.Integral$",{pc:1,a:1,c:1});var Db;function Gb(){}Gb.prototype=new u;Gb.prototype.constructor=Gb;Gb.prototype.$classData=x({qc:0},"scala.math.Numeric$",{qc:1,a:1,c:1});var Fb;function uc(){}uc.prototype=new u;uc.prototype.constructor=uc;function vc(){}vc.prototype=uc.prototype;uc.prototype.j=function(){return"\x3cfunction0\x3e"};function wc(a){this.Va=a}wc.prototype=new u;wc.prototype.constructor=wc;
wc.prototype.j=function(){return""+this.Va};wc.prototype.$classData=x({ud:0},"scala.runtime.IntRef",{ud:1,a:1,c:1});function yc(a){this.Wa=a}yc.prototype=new u;yc.prototype.constructor=yc;yc.prototype.j=function(){return""+this.Wa};yc.prototype.$classData=x({vd:0},"scala.runtime.ObjectRef",{vd:1,a:1,c:1});function Kb(){}Kb.prototype=new u;Kb.prototype.constructor=Kb;Kb.prototype.$classData=x({vc:0},"scala.util.Either$",{vc:1,a:1,c:1});var Jb;function H(){}H.prototype=new u;
H.prototype.constructor=H;H.prototype.j=function(){return"Left"};H.prototype.$classData=x({wc:0},"scala.util.Left$",{wc:1,a:1,c:1});var Lb;function zc(){this.Na=null}zc.prototype=new u;zc.prototype.constructor=zc;function Ac(){}Ac.prototype=zc.prototype;
function Bc(){Cc||(Cc=new Dc);var a=Cc;return Ec(G(),new R((b=>()=>{var c=b.Na;var d=62;if(0>=d)throw c=new Fc,Q(c,"n must be positive"),c;if((d&(-d|0))===d)c=oc(c)>>Math.clz32(d);else a:for(;;){var g=oc(c);var e=g;var k=d;if(0===k)throw new Gc;e=e%k|0;if(!(0>((g-e|0)+(-1+d|0)|0))){c=e;break a}}c=65535&("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charCodeAt(c)|0);return new h(c)})(a)))}function I(){}I.prototype=new u;I.prototype.constructor=I;I.prototype.j=function(){return"Right"};
I.prototype.$classData=x({yc:0},"scala.util.Right$",{yc:1,a:1,c:1});var Mb;function Hc(){this.nb=this.sa=0;Ic=this;this.sa=r("Seq");this.nb=r("Map");r("Set");kb||(kb=new jb);for(var a=this.nb,b=0,c=0,d=0,g=1,e=kb.lb.o();e.h();){var k=e.f();k=M(N(),k);b=b+k|0;c^=k;g=Math.imul(g,1|k);d=1+d|0}a=O(a,b);a=O(a,c);a=bc(a,g);P(a^d)}Hc.prototype=new ac;Hc.prototype.constructor=Hc;Hc.prototype.$classData=x({zc:0},"scala.util.hashing.MurmurHash3$",{zc:1,Hd:1,a:1});var Ic;
function Jc(){Ic||(Ic=new Hc);return Ic}function Kc(){Lc=this}Kc.prototype=new u;Kc.prototype.constructor=Kc;Kc.prototype.$classData=x({Hb:0},"viz.vega.facades.EmbedOptions$",{Hb:1,a:1,Ad:1});var Lc;class Mc extends mc{}function Nc(){}Nc.prototype=new u;Nc.prototype.constructor=Nc;function Oc(){}Oc.prototype=Nc.prototype;function Pc(){this.D=null;Qc=this;this.D=new Rc}Pc.prototype=new u;Pc.prototype.constructor=Pc;Pc.prototype.$classData=x({Fc:0},"scala.collection.Iterator$",{Fc:1,a:1,F:1,c:1});var Qc;
function D(){Qc||(Qc=new Pc);return Qc}function S(a,b){this.Yc=a;this.Zc=b}S.prototype=new u;S.prototype.constructor=S;S.prototype.n=function(){return this.Yc};S.prototype.i=function(){return this.Zc};S.prototype.$classData=x({Xc:0},"scala.collection.immutable.LazyList$State$Cons",{Xc:1,a:1,Wc:1,c:1});function T(){}T.prototype=new u;T.prototype.constructor=T;T.prototype.R=function(){throw new Sc("head of empty lazy list");};T.prototype.i=function(){throw new Tc("tail of empty lazy list");};
T.prototype.n=function(){this.R()};T.prototype.$classData=x({$c:0},"scala.collection.immutable.LazyList$State$Empty$",{$c:1,a:1,Wc:1,c:1});var Uc;function Vc(){Uc||(Uc=new T);return Uc}function Ab(){}Ab.prototype=new u;Ab.prototype.constructor=Ab;Ab.prototype.$classData=x({nc:0},"scala.math.Equiv$",{nc:1,a:1,Ed:1,c:1});var zb;function Ib(){}Ib.prototype=new u;Ib.prototype.constructor=Ib;Ib.prototype.$classData=x({sc:0},"scala.math.Ordering$",{sc:1,a:1,Fd:1,c:1});var Hb;function R(a){this.Ab=a}
R.prototype=new vc;R.prototype.constructor=R;R.prototype.$classData=x({rd:0},"scala.scalajs.runtime.AnonFunction0",{rd:1,ee:1,a:1,xd:1});function Dc(){this.Na=null;var a=new nc;rc||(rc=new qc);var b=pc();var c=pc();b=new l(c,b);c=-554899859^b.l;a.Ia=c>>>24|0|(65535&(5^b.k))<<8;a.Ja=16777215&c;a.jc=!1;this.Na=a}Dc.prototype=new Ac;Dc.prototype.constructor=Dc;Dc.prototype.$classData=x({xc:0},"scala.util.Random$",{xc:1,Gd:1,a:1,c:1});var Cc;function Wc(){}Wc.prototype=new u;
Wc.prototype.constructor=Wc;function Xc(){}Xc.prototype=Wc.prototype;class U extends Mc{}U.prototype.$classData=x({w:0},"java.lang.RuntimeException",{w:1,z:1,A:1,a:1,c:1});function Za(a){a.b="";return a}function B(){this.b=null}B.prototype=new u;B.prototype.constructor=B;B.prototype.j=function(){return this.b};B.prototype.g=function(){return this.b.length|0};B.prototype.$classData=x({Xb:0},"java.lang.StringBuilder",{Xb:1,a:1,Nb:1,Kb:1,c:1});function Yc(){}Yc.prototype=new u;
Yc.prototype.constructor=Yc;function Zc(){}f=Zc.prototype=Yc.prototype;f.o=function(){return this};f.e=function(){return!this.h()};f.la=function(a){return this.Ea(a,-1)};f.Ea=function(a,b){a=0<a?a:0;b=0>b?-1:b<=a?0:b-a|0;return 0===b?D().D:new $c(this,a,b)};f.j=function(){return"\x3citerator\x3e"};f.ja=function(a,b,c,d){return $a(this,a,b,c,d)};f.s=function(){return-1};function C(){ad||(ad=new bd)}C.prototype=new Oc;C.prototype.constructor=C;
C.prototype.$classData=x({Dc:0},"scala.collection.Iterable$",{Dc:1,Ec:1,a:1,F:1,c:1});var lb;function cd(){}cd.prototype=new u;cd.prototype.constructor=cd;function dd(){}dd.prototype=cd.prototype;function ed(a,b){var c=a.s();if(-1!==c){var d=b.s();c=-1!==d&&c!==d}else c=!1;if(c)return!1;a:{a=a.o();for(b=b.o();a.h()&&b.h();)if(!K(L(),a.f(),b.f())){b=!1;break a}b=a.h()===b.h()}return b}function bd(){qb()}bd.prototype=new Oc;bd.prototype.constructor=bd;
bd.prototype.$classData=x({Sc:0},"scala.collection.immutable.Iterable$",{Sc:1,Ec:1,a:1,F:1,c:1});var ad;function fd(){this.Ca=null;gd=this;this.Ca=hd(new V(new R(()=>Vc())))}fd.prototype=new u;fd.prototype.constructor=fd;function id(a,b,c){return new V(new R(((d,g)=>()=>{for(var e=d.Wa,k=g.Va;0<k&&!e.e();)e=W(e).i(),d.Wa=e,k=-1+k|0,g.Va=k;return W(e)})(new yc(b),new wc(c))))}function Ec(a,b){return new V(new R((c=>()=>{G();var d=(0,c.Ab)(),g=Ec(G(),c);return new S(d,g)})(b)))}
fd.prototype.$classData=x({Uc:0},"scala.collection.immutable.LazyList$",{Uc:1,a:1,da:1,F:1,c:1});var gd;function G(){gd||(gd=new fd);return gd}function tb(){}tb.prototype=new u;tb.prototype.constructor=tb;tb.prototype.$classData=x({jd:0},"scala.collection.immutable.Stream$",{jd:1,a:1,da:1,F:1,c:1});var sb;function jd(){}jd.prototype=new Xc;jd.prototype.constructor=jd;function kd(){}kd.prototype=jd.prototype;class Gc extends U{constructor(){super();Q(this,"/ by zero")}}
Gc.prototype.$classData=x({Lb:0},"java.lang.ArithmeticException",{Lb:1,w:1,z:1,A:1,a:1,c:1});class Fc extends U{}Fc.prototype.$classData=x({cb:0},"java.lang.IllegalArgumentException",{cb:1,w:1,z:1,A:1,a:1,c:1});class ld extends U{constructor(a){super();Q(this,a)}}ld.prototype.$classData=x({Qb:0},"java.lang.IndexOutOfBoundsException",{Qb:1,w:1,z:1,A:1,a:1,c:1});x({Tb:0},"java.lang.JSConsoleBasedPrintStream$DummyOutputStream",{Tb:1,Eb:1,a:1,Cb:1,Mb:1,Db:1});
x({Vb:0},"java.lang.NullPointerException",{Vb:1,w:1,z:1,A:1,a:1,c:1});class Tc extends U{constructor(a){super();Q(this,a)}}Tc.prototype.$classData=x({cc:0},"java.lang.UnsupportedOperationException",{cc:1,w:1,z:1,A:1,a:1,c:1});class Sc extends U{constructor(a){super();Q(this,a)}}Sc.prototype.$classData=x({gc:0},"java.util.NoSuchElementException",{gc:1,w:1,z:1,A:1,a:1,c:1});
class md extends U{constructor(a){super();this.kb=null;this.La=!1;this.ra=a;Q(this,null)}ma(){if(!this.La&&!this.La){if(null===this.ra)var a="null";else try{a=ja(this.ra)+" (of class "+ea(this.ra)+")"}catch(b){if(Yb||(Yb=new Xb),null!==(b instanceof mc?b:new nd(b)))a="an instance of class "+ea(this.ra);else throw b;}this.kb=a;this.La=!0}return this.kb}}md.prototype.$classData=x({lc:0},"scala.MatchError",{lc:1,w:1,z:1,A:1,a:1,c:1});function Rc(){}Rc.prototype=new Zc;Rc.prototype.constructor=Rc;f=Rc.prototype;
f.h=function(){return!1};f.s=function(){return 0};f.Ea=function(){return this};f.f=function(){throw new Sc("next on empty iterator");};f.$classData=x({Gc:0},"scala.collection.Iterator$$anon$19",{Gc:1,Oa:1,a:1,ya:1,B:1,C:1});function od(a){for(;0<a.L;)a.T.h()?(a.T.f(),a.L=-1+a.L|0):a.L=0}function pd(a,b){if(0>a.v)return-1;a=a.v-b|0;return 0>a?0:a}function $c(a,b,c){this.T=a;this.v=c;this.L=b}$c.prototype=new Zc;$c.prototype.constructor=$c;f=$c.prototype;
f.s=function(){var a=this.T.s();if(0>a)return-1;a=a-this.L|0;a=0>a?0:a;if(0>this.v)return a;var b=this.v;return b<a?b:a};f.h=function(){od(this);return 0!==this.v&&this.T.h()};f.f=function(){od(this);return 0<this.v?(this.v=-1+this.v|0,this.T.f()):0>this.v?this.T.f():D().D.f()};f.Ea=function(a,b){a=0<a?a:0;if(0>b)b=pd(this,a);else if(b<=a)b=0;else if(0>this.v)b=b-a|0;else{var c=pd(this,a);b=b-a|0;b=c<b?c:b}if(0===b)return D().D;this.L=this.L+a|0;this.v=b;return this};
f.$classData=x({Hc:0},"scala.collection.Iterator$SliceIterator",{Hc:1,Oa:1,a:1,ya:1,B:1,C:1});function qd(a,b){if(0>b)throw new ld(""+b);a=a.Za(b);if(a.e())throw new ld(""+b);return a.n()}function rd(a,b){if(b&&b.$classData&&b.$classData.r.qb)a:for(;;){if(a===b){a=!0;break a}if((a.e()?0:!b.e())&&K(L(),a.n(),b.n()))a=a.Y(),b=b.Y();else{a=a.e()&&b.e();break a}}else a=ed(a,b);return a}function pb(){ub()}pb.prototype=new dd;pb.prototype.constructor=pb;
pb.prototype.$classData=x({Rc:0},"scala.collection.immutable.IndexedSeq$",{Rc:1,Jc:1,a:1,da:1,F:1,c:1});var ob;function X(a){this.ea=a}X.prototype=new Zc;X.prototype.constructor=X;X.prototype.h=function(){return!this.ea.e()};X.prototype.f=function(){if(this.ea.e())return D().D.f();var a=W(this.ea).n();this.ea=W(this.ea).i();return a};X.prototype.$classData=x({Vc:0},"scala.collection.immutable.LazyList$LazyIterator",{Vc:1,Oa:1,a:1,ya:1,B:1,C:1});function sd(){td=this;E();E()}sd.prototype=new u;
sd.prototype.constructor=sd;sd.prototype.$classData=x({cd:0},"scala.collection.immutable.List$",{cd:1,a:1,Lc:1,da:1,F:1,c:1});var td;function qb(){td||(td=new sd)}
function ud(a){a.q<=a.m&&D().D.f();a.ga=1+a.ga|0;for(var b=null;0===b.d.length;)a.ga=1+a.ga|0,b=null;a.Da=a.V;var c=a.ed/2|0,d=a.ga-c|0;a.Q=(1+c|0)-(0>d?-d|0:d)|0;c=a.Q;switch(c){case 1:a.G=b;break;case 2:a.N=b;break;case 3:a.O=b;break;case 4:a.P=b;break;case 5:a.U=b;break;case 6:a.Ta=b;break;default:throw new md(c);}a.V=a.Da+Math.imul(b.d.length,1<<Math.imul(5,-1+a.Q|0))|0;a.V>a.H&&(a.V=a.H);1<a.Q&&(a.fa=-1+(1<<Math.imul(5,a.Q))|0)}
function vd(a,b,c){this.Ta=this.U=this.P=this.O=this.N=null;this.H=b;this.ed=c;this.G=a.W;this.M=this.G.d.length;this.fa=this.m=0;this.q=this.H;this.ga=0;this.Q=1;this.Da=0;this.V=this.M}vd.prototype=new u;vd.prototype.constructor=vd;f=vd.prototype;f.o=function(){return this};f.e=function(){return this.q<=this.m};f.j=function(){return"\x3citerator\x3e"};f.ja=function(a,b,c,d){return $a(this,a,b,c,d)};f.s=function(){return this.q-this.m|0};f.h=function(){return this.q>this.m};
f.f=function(){if(this.m===this.M){var a=(this.m-this.q|0)+this.H|0;a===this.V&&ud(this);if(1<this.Q){a=a-this.Da|0;var b=this.fa^a;1024>b?this.G=this.N.d[31&(a>>>5|0)]:(32768>b?this.N=this.O.d[31&(a>>>10|0)]:(1048576>b?this.O=this.P.d[31&(a>>>15|0)]:(33554432>b?this.P=this.U.d[31&(a>>>20|0)]:(this.U=this.Ta.d[a>>>25|0],this.P=this.U.d[0]),this.O=this.P.d[0]),this.N=this.O.d[0]),this.G=this.N.d[0]);this.fa=a}this.q=this.q-this.m|0;a=this.G.d.length;b=this.q;this.M=a<b?a:b;this.m=0}a=this.G.d[this.m];
this.m=1+this.m|0;return a};
f.la=function(a){if(0<a){a=((this.m-this.q|0)+this.H|0)+a|0;var b=this.H;a=a<b?a:b;if(a===this.H)this.M=this.q=this.m=0;else{for(;a>=this.V;)ud(this);b=a-this.Da|0;if(1<this.Q){var c=this.fa^b;1024>c||(32768>c||(1048576>c||(33554432>c||(this.U=this.Ta.d[b>>>25|0]),this.P=this.U.d[31&(b>>>20|0)]),this.O=this.P.d[31&(b>>>15|0)]),this.N=this.O.d[31&(b>>>10|0)]);this.G=this.N.d[31&(b>>>5|0)];this.fa=b}this.M=this.G.d.length;this.m=31&b;this.q=this.m+(this.H-a|0)|0;this.M>this.q&&(this.M=this.q)}}return this};
f.$classData=x({dd:0},"scala.collection.immutable.NewVectorIterator",{dd:1,a:1,ya:1,B:1,C:1,Ga:1});function nb(){qb()}nb.prototype=new dd;nb.prototype.constructor=nb;nb.prototype.$classData=x({hd:0},"scala.collection.immutable.Seq$",{hd:1,Jc:1,a:1,da:1,F:1,c:1});var mb;
function wd(){this.Ua=0;this.yb=null;xd=this;try{var a=Ja;Ia||(Ia=new Ha);var b=a(Ia,"scala.collection.immutable.Vector.defaultApplyPreferredMaxLength","250");lc||(lc=new kc);var c=null===b?0:b.length|0;0===c&&ic(b);var d=65535&(b.charCodeAt(0)|0),g=(a=45===d)?2147483648:2147483647;d=a||43===d?1:0;d>=(b.length|0)&&ic(b);for(var e=0;d!==c;){hc||(hc=new gc);var k=hc,m=65535&(b.charCodeAt(d)|0);if(256>m)var t=48<=m&&57>=m?-48+m|0:65<=m&&90>=m?-55+m|0:97<=m&&122>=m?-87+m|0:-1;else if(65313<=m&&65338>=
m)t=-65303+m|0;else if(65345<=m&&65370>=m)t=-65335+m|0;else{var ec=fc(k);Pa||(Pa=new Oa);b:for(var J=ec,Jd=m,Tb=0,xc=J.d.length;;){if(Tb===xc){var Ub=-1-Tb|0;break b}var Vb=(Tb+xc|0)>>>1|0,Kd=J.d[Vb];if(Jd<Kd)xc=Vb;else{if(K(L(),Jd,Kd)){Ub=Vb;break b}Tb=1+Vb|0}}J=0>Ub?-2-Ub|0:Ub;if(0>J)t=-1;else{var Ld=m-fc(k).d[J]|0;t=9<Ld?-1:Ld}}var Md=10>t?t:-1;e=10*e+Md;(-1===Md||e>g)&&ic(b);d=1+d|0}}catch(ie){throw ie;}this.Ua=a?-e|0:e|0;this.yb=new vd(yd(),0,0)}wd.prototype=new u;wd.prototype.constructor=wd;
wd.prototype.$classData=x({ld:0},"scala.collection.immutable.Vector$",{ld:1,a:1,Lc:1,da:1,F:1,c:1});var xd;function ub(){xd||(xd=new wd);return xd}function ia(a){a=+a;return Ca(Da(),a)}class jc extends Fc{constructor(a){super();Q(this,a)}}jc.prototype.$classData=x({Wb:0},"java.lang.NumberFormatException",{Wb:1,cb:1,w:1,z:1,A:1,a:1,c:1});function r(a){for(var b=0,c=1,d=-1+(a.length|0)|0;0<=d;)b=b+Math.imul(65535&(a.charCodeAt(d)|0),c)|0,c=Math.imul(31,c),d=-1+d|0;return b}function zd(){}
zd.prototype=new u;zd.prototype.constructor=zd;function Ad(){}Ad.prototype=zd.prototype;zd.prototype.ka=function(){return this.X()};zd.prototype.ja=function(a,b,c,d){return $a(this,a,b,c,d)};function Bd(a){this.p=0;this.Cc=a;this.K=0;this.p=a.g()}Bd.prototype=new Zc;Bd.prototype.constructor=Bd;f=Bd.prototype;f.s=function(){return this.p};f.h=function(){return 0<this.p};f.f=function(){if(0<this.p){var a=this.Cc.u(this.K);this.K=1+this.K|0;this.p=-1+this.p|0;return a}return D().D.f()};
f.la=function(a){0<a&&(this.K=this.K+a|0,a=this.p-a|0,this.p=0>a?0:a);return this};f.Ea=function(a,b){a=0>a?0:a>this.p?this.p:a;b=(0>b?0:b>this.p?this.p:b)-a|0;this.p=0>b?0:b;this.K=this.K+a|0;return this};f.$classData=x({Bc:0},"scala.collection.IndexedSeqView$IndexedSeqViewIterator",{Bc:1,Oa:1,a:1,ya:1,B:1,C:1,c:1});function Cd(){}Cd.prototype=new kd;Cd.prototype.constructor=Cd;function Dd(){}Dd.prototype=Cd.prototype;
class nd extends U{constructor(a){super();this.ha=a;Q(this,null)}ma(){return ja(this.ha)}$a(){}Ka(){return"JavaScriptException"}hb(){return 1}ib(a){if(0===a)a=this.ha;else throw N(),new ld(""+a);return a}E(){Jc();var a=this.hb();if(0===a)a=r(this.Ka());else{var b=O(-889275714,r(this.Ka()));for(var c=0;c<a;){var d=this.ib(c);b=O(b,M(N(),d));c=1+c|0}a=P(b^a)}return a}y(a){if(this===a)return!0;if(a instanceof nd){var b=this.ha;a=a.ha;return K(L(),b,a)}return!1}}
nd.prototype.$classData=x({qd:0},"scala.scalajs.js.JavaScriptException",{qd:1,w:1,z:1,A:1,a:1,c:1,mc:1,qa:1});function A(a){this.Ub=a;this.pa=""}A.prototype=new Dd;A.prototype.constructor=A;A.prototype.$classData=x({Sb:0},"java.lang.JSConsoleBasedPrintStream",{Sb:1,zd:1,yd:1,Eb:1,a:1,Cb:1,Mb:1,Db:1,Kb:1});function Ed(){}Ed.prototype=new Ad;Ed.prototype.constructor=Ed;function Fd(){}Fd.prototype=Ed.prototype;Ed.prototype.j=function(){return this.X()+"(\x3cnot computed\x3e)"};
function Gd(a,b){return a===b?!0:b&&b.$classData&&b.$classData.r.za&&b.Ya(a)?a.ta(b):!1}function Hd(){}Hd.prototype=new Ad;Hd.prototype.constructor=Hd;function Id(){}f=Id.prototype=Hd.prototype;f.Ya=function(){return!0};f.y=function(a){return Gd(this,a)};
f.E=function(){var a=Jc();if(this&&this.$classData&&this.$classData.r.ob)a:{var b=a.sa;a=this.g();switch(a){case 0:a=P(b^0);break a;case 1:a=b;b=this.u(0);a=P(O(a,M(N(),b))^1);break a;default:var c=this.u(0),d=M(N(),c);c=b=O(b,d);var g=this.u(1);g=M(N(),g);var e=g-d|0;for(d=2;d<a;){b=O(b,g);var k=this.u(d);k=M(N(),k);if(e!==(k-g|0)){b=O(b,k);for(d=1+d|0;d<a;)c=this.u(d),b=O(b,M(N(),c)),d=1+d|0;a=P(b^a);break a}g=k;d=1+d|0}a=P(O(O(c,e),g))}}else if(this instanceof Nd){for(a=a.sa;!this.e();)this.R();
a=P(a^0)}else a:if(b=a.sa,a=this.o(),a.h())if(c=a.f(),a.h()){d=a.f();e=M(N(),c);c=b=O(b,e);g=M(N(),d);e=g-e|0;for(d=2;a.h();){b=O(b,g);k=a.f();k=M(N(),k);if(e!==(k-g|0)){b=O(b,k);for(d=1+d|0;a.h();)c=a.f(),b=O(b,M(N(),c)),d=1+d|0;a=P(b^d);break a}g=k;d=1+d|0}a=P(O(O(c,e),g))}else a=P(O(b,M(N(),c))^1);else a=P(b^0);return a};f.j=function(){return Xa(this,this.ka()+"(",", ",")")};f.e=function(){return 0===this.ca(0)};f.ta=function(a){return ed(this,a)};function Od(){}Od.prototype=new Fd;
Od.prototype.constructor=Od;function Pd(){}Pd.prototype=Od.prototype;function Y(){this.Ba=null}Y.prototype=new Pd;Y.prototype.constructor=Y;function Qd(){}Qd.prototype=Y.prototype;Y.prototype.u=function(a){return this.Ba.u(a)};Y.prototype.g=function(){return this.Ba.g()};Y.prototype.e=function(){return this.Ba.e()};function Rd(a){this.Ba=a}Rd.prototype=new Qd;Rd.prototype.constructor=Rd;f=Rd.prototype;f.o=function(){return new Bd(this)};f.X=function(){return"IndexedSeqView"};
f.ca=function(a){var b=this.g();return b===a?0:b<a?-1:1};f.s=function(){return this.g()};f.$classData=x({Ac:0},"scala.collection.IndexedSeqView$Id",{Ac:1,Md:1,Id:1,Jd:1,ua:1,a:1,va:1,B:1,xa:1,C:1,wa:1,Od:1,c:1,Ld:1,Aa:1,Kd:1,pb:1});function Sd(){}Sd.prototype=new Id;Sd.prototype.constructor=Sd;function Td(){}Td.prototype=Sd.prototype;function Ud(){}Ud.prototype=new Id;Ud.prototype.constructor=Ud;function Vd(){}Vd.prototype=Ud.prototype;
var Xd=function Wd(a,b){if(0>=b)return G().Ca;G();return new V(new R(((d,g)=>()=>{if(d.e())return Vc();G();var e=W(d).n(),k=Wd(W(d).i(),-1+g|0);return new S(e,k)})(a,b)))};
function Yd(a,b,c,d,g){b.b=""+b.b+c;if(!a.t)b.b+="\x3cnot computed\x3e";else if(!a.e()){c=W(a).n();b.b=""+b.b+c;c=a;var e=W(a).i();if(c!==e&&(!e.t||W(c)!==W(e))&&(c=e,e.t&&!e.e()))for(e=W(e).i();c!==e&&e.t&&!e.e()&&W(c)!==W(e);){b.b=""+b.b+d;var k=W(c).n();b.b=""+b.b+k;c=W(c).i();e=W(e).i();e.t&&!e.e()&&(e=W(e).i())}if(!e.t||e.e()){for(;c!==e;)b.b=""+b.b+d,a=W(c).n(),b.b=""+b.b+a,c=W(c).i();c.t||(b.b=""+b.b+d,b.b+="\x3cnot computed\x3e")}else{k=a;for(a=0;;){var m=k,t=e;if(m!==t&&W(m)!==W(t))k=W(k).i(),
e=W(e).i(),a=1+a|0;else break}k=c;m=e;(k===m||W(k)===W(m))&&0<a&&(b.b=""+b.b+d,a=W(c).n(),b.b=""+b.b+a,c=W(c).i());for(;;)if(a=c,k=e,a!==k&&W(a)!==W(k))b.b=""+b.b+d,a=W(c).n(),b.b=""+b.b+a,c=W(c).i();else break;b.b=""+b.b+d;b.b+="\x3ccycle\x3e"}}b.b=""+b.b+g;return b}function V(a){this.vb=null;this.Ra=!1;this.ub=a;this.Sa=this.t=!1}V.prototype=new Td;V.prototype.constructor=V;f=V.prototype;f.X=function(){return"LinearSeq"};f.g=function(){for(var a=this,b=0;!a.e();)b=1+b|0,a=a.Y();return b};
f.ca=function(a){if(0>a)a=1;else a:for(var b=this,c=0;;){if(c===a){a=b.e()?0:1;break a}if(b.e()){a=-1;break a}c=1+c|0;b=b.Y()}return a};f.u=function(a){return qd(this,a)};f.ta=function(a){return rd(this,a)};function W(a){if(!a.Ra&&!a.Ra){if(a.Sa)throw Yb||(Yb=new Xb),a=new U,Q(a,"self-referential LazyList or a derivation thereof has no more elements"),a instanceof nd?a.ha:a;a.Sa=!0;try{var b=(0,a.ub.Ab)()}finally{a.Sa=!1}a.t=!0;a.ub=null;a.vb=b;a.Ra=!0}return a.vb}
f.e=function(){return W(this)===Vc()};f.s=function(){return this.t&&this.e()?0:-1};f.n=function(){return W(this).n()};function hd(a){var b=a,c=a;for(b.e()||(b=W(b).i());c!==b&&!b.e();){b=W(b).i();if(b.e())break;b=W(b).i();if(b===c)break;c=W(c).i()}return a}f.o=function(){return this.t&&this.e()?D().D:new X(this)};f.ka=function(){return"LazyList"};f.ja=function(a,b,c,d){hd(this);Yd(this,a.x,b,c,d);return a};f.j=function(){var a=new B;Za(a);a.b="LazyList";return Yd(this,a,"(",", ",")").b};
f.Za=function(a){return 0>=a?this:this.t&&this.e()?G().Ca:id(G(),this,a)};f.Y=function(){return W(this).i()};f.$classData=x({Tc:0},"scala.collection.immutable.LazyList",{Tc:1,rb:1,Pa:1,ua:1,a:1,va:1,B:1,xa:1,C:1,wa:1,za:1,Ma:1,Fa:1,Aa:1,qa:1,wb:1,tb:1,xb:1,ad:1,qb:1,Ic:1,bd:1,c:1});function Zd(){this.W=null}Zd.prototype=new Td;Zd.prototype.constructor=Zd;function $d(){}f=$d.prototype=Zd.prototype;f.Ya=function(a){return a&&a.$classData&&a.$classData.r.sb?this.g()===a.g():!0};
f.ta=function(a){if(a&&a.$classData&&a.$classData.r.sb)if(this===a)var b=!0;else{var c=this.g();if(b=c===a.g()){var d=0,g=ub().Ua,e=ub().Ua;g=g<e?g:e;e=c>>31;var k=g>>>31|0|g>>31<<1;for(g=(e===k?(-2147483648^c)>(-2147483648^g<<1):e>k)?g:c;d<g&&b;)L(),ae(d),b=K(0,void 0,ae(d)),d=1+d|0;if(d<c&&b)for(c=this.o().la(d),a=a.o().la(d);b&&c.h();)b=K(L(),c.f(),a.f())}}else b=ed(this,a);return b};f.X=function(){return"IndexedSeq"};f.ca=function(a){var b=this.g();return b===a?0:b<a?-1:1};f.s=function(){return this.g()};
f.g=function(){return this instanceof be?this.Qa:this.W.d.length};f.o=function(){return yd()===this?ub().yb:new vd(this,this.g(),0)};f.ka=function(){return"Vector"};function Nd(){}Nd.prototype=new Td;Nd.prototype.constructor=Nd;function ce(){}f=ce.prototype=Nd.prototype;f.X=function(){return"LinearSeq"};f.u=function(a){return qd(this,a)};f.ta=function(a){return rd(this,a)};f.e=function(){return this===E()};f.g=function(){for(var a=0;!this.e();)a=1+a|0,de();return a};
f.ca=function(a){if(0>a)a=1;else a:for(;;){if(0===a){a=this.e()?0:1;break a}if(this.e()){a=-1;break a}de()}return a};f.ka=function(){return"List"};f.y=function(a){if(a instanceof Nd)a:for(;;){if(this===a){a=!0;break a}var b=this.e(),c=a.e();if(b||c)d=!1;else{L();this.R();var d=K(0,void 0,a.R())}if(d)de();else{a=b&&c;break a}}else a=Gd(this,a);return a};f.Za=function(a){a:for(var b=this;;){if(0>=a||b.e())break a;a=-1+a|0;b=b.Y()}return b};function ee(){this.W=null}ee.prototype=new $d;
ee.prototype.constructor=ee;function fe(){}fe.prototype=ee.prototype;function be(){this.W=null;this.Qa=0}be.prototype=new fe;be.prototype.constructor=be;function ge(){}ge.prototype=be.prototype;function he(){je=this;E();E()}he.prototype=new ce;he.prototype.constructor=he;f=he.prototype;f.R=function(){throw new Sc("head of empty list");};function de(){throw new Tc("tail of empty list");}f.s=function(){return 0};f.o=function(){return D().D};f.Ka=function(){return"Nil"};f.hb=function(){return 0};
f.ib=function(a){N();throw new ld(""+a);};f.Y=function(){de()};f.n=function(){this.R()};f.$classData=x({fd:0},"scala.collection.immutable.Nil$",{fd:1,Rd:1,rb:1,Pa:1,ua:1,a:1,va:1,B:1,xa:1,C:1,wa:1,za:1,Ma:1,Fa:1,Aa:1,qa:1,wb:1,tb:1,xb:1,ad:1,qb:1,Ic:1,bd:1,Nd:1,Mc:1,Kc:1,kd:1,Pc:1,c:1,mc:1});var je;function E(){je||(je=new he);return je}function Z(){this.W=null;this.Qa=0;var a=cb().zb;cb();this.Qa=0;this.W=a}Z.prototype=new ge;Z.prototype.constructor=Z;
function ae(a){throw new ld(a+" is out of bounds (empty vector)");}Z.prototype.y=function(a){return this===a||!(a instanceof Zd)&&Gd(this,a)};Z.prototype.u=function(a){ae(a)};Z.prototype.$classData=x({md:0},"scala.collection.immutable.Vector0$",{md:1,Pd:1,Td:1,Sd:1,rb:1,Pa:1,ua:1,a:1,va:1,B:1,xa:1,C:1,wa:1,za:1,Ma:1,Fa:1,Aa:1,qa:1,wb:1,tb:1,xb:1,sb:1,ob:1,pb:1,Qd:1,kd:1,Mc:1,Kc:1,Pc:1,c:1});var ke;function yd(){ke||(ke=new Z);return ke}function Ya(){this.x=null}Ya.prototype=new Vd;
Ya.prototype.constructor=Ya;f=Ya.prototype;f.X=function(){return"IndexedSeq"};f.o=function(){var a=new Rd(this);return new Bd(a)};f.ca=function(a){var b=this.x.g();return b===a?0:b<a?-1:1};f.g=function(){return this.x.g()};f.s=function(){return this.x.g()};f.j=function(){return this.x.b};f.e=function(){return 0===this.x.g()};f.u=function(a){return new h(65535&(this.x.b.charCodeAt(a)|0))};
f.$classData=x({od:0},"scala.collection.mutable.StringBuilder",{od:1,Ud:1,Pa:1,ua:1,a:1,va:1,B:1,xa:1,C:1,wa:1,za:1,Ma:1,Fa:1,Aa:1,qa:1,ce:1,ae:1,de:1,Xd:1,Ga:1,be:1,Vd:1,Yd:1,Wd:1,Zd:1,ob:1,pb:1,$d:1,Nb:1,c:1});ca=new l(0,0);za.Bb=ca;
exports.mdoc_js_run0=function(a){Ra||(Ra=new Qa);dc||(dc=new cc);tc||(tc=new sc);var b=tc.jb.mb;for(var c="here!\n";""!==c;){var d=c.indexOf("\n")|0;if(0>d)b.pa=""+b.pa+c,c="";else{var g=""+b.pa+c.substring(0,d);"undefined"!==typeof console&&(b.Ub&&console.error?console.error(g):console.log(g));b.pa="";c=c.substring(1+d|0)}}c=document.createElement("div");b=Bc();b=b.t&&b.e()?G().Ca:Xd(b,8);b="vega"+Xa(b,"","","");c.id=b;a.appendChild(c);c.setAttribute("style","width:0vmin;height:0vmin");Lc||(Lc=new Kc);
a=Lc;c=new XMLHttpRequest;c.open("GET","../assets/desktopBrowser.json",!1);c.send();c=JSON.parse(c.responseText);(aa&&"object"===typeof aa&&"default"in aa?aa["default"]:aa)("#"+b,c,a)};
