addSbtPlugin("org.typelevel" % "sbt-typelevel" % "0.4.5")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.3")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.9.34")
addSbtPlugin("org.typelevel" % "sbt-typelevel-site" % "0.4.5")
addSbtPlugin("org.scalameta" % "sbt-mdoc" % "2.2.24")
