addSbtPlugin("org.typelevel" % "sbt-typelevel" % "0.5.4")
addSbtPlugin("org.typelevel" % "sbt-typelevel-site" % "0.5.4")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.14.0")
addSbtPlugin("com.timushev.sbt" % "sbt-updates" % "0.6.4")
//addSbtPlugin("com.mayreh" % "sbt-thank-you-stars" % "0.2")
//addSbtPlugin("org.scalablytyped.converter" % "sbt-converter" % "1.0.0-beta41")
